### ISSUE TITLE
issue-1: figma todo - layout composition

### ISSUE THREAD

**Issue by e-jieun** [e-jieun/portfolio_e-jieun#2]
# Layout Composition
### Figma

- [x] 레이아웃 섹셔닝

1. 메인 페이지
- [x] 메인 페이지의 파도의 이미지 부분 페이지 레이아웃 구성
- [ ] 메인 페이지 서핑과 서퍼의 연출 포인트를 잡아내는 구성으로 작성

2. 자기소개 페이지
- 자기 소개에 필수인 정보들을 빼놓지 말고 구성하기
- [x] 깃허브 주소
- [x] 노션 페이지로 자기소개서 주소를 달아두기
- [ ] 노션 페이지 자기소개서 페이지 작성
- [x] 사진말고 memoji의 어떤 모습을 나 자신의 프로필로 활용할 것인지 결정

3. 포트폴리오 소개 페이지
- [x] 프로젝트의 소개 부분과 서핑을 활용한 연출 포인트 구성을 레이아웃 구성으로 작성
- 보라도라
- 가상 문구류 체험
- 더발룬티어스 

4. 하단의 footer 마지막 페이지
- [x] 'shaka'를 활용한 마지막 페이지 구성
- [x] 'shaka'란 인사가 너무 캐주얼 해 보이지 않도록 구성해보는 방안
- [x] 'shaka'의 이미지와 함께 텍스트를 구성하는 단편적인 방법을 탈피하는 레이아웃으로 구성을 해 작성

**Comment by e-jieun** [comment]
# Layout Composition
## 05/25
### Figma
- [x] 레이아웃 구성 단계

1. 메인 페이지
- [x] 메인 페이지 서핑, 서퍼의 연출 포인트 잡아내는 구성
- [x] 파도 부분을 어떻게 해결할 것인지 레이아웃 구성할 때 꼭 생각하고 설계해두자
- [x] 작성하고 나서 파도 부분 codepen 인터랙션(pin 해둔 파도 인터랙션) 실험해보기

2. 자기소개 페이지
- [ ] 노션 페이지 자기소개서 페이지 작성

3. 포트폴리오 소개 페이지
- [x] 프로젝트 소개 부분과 서핑을 활용한 연출 포인트 구성 -> 레이아웃 구성
- [x] 노션 페이지 고려해야 할 것

4. 최하단 footer 페이지
- [x] 하단 footer 페이지 설명 텍스트와 함께 구성하는 단편적인 방법을 탈피하는 레이아웃 구성

**Comment by e-jieun** [comment]
# Layout Composition

### Figma
### 레이아웃 섹셔닝 바탕으로 해결해야 할 부분들
- [x] 페르소나 작성 다시 정리
- [x] 사용자 여정지도 작성 다시 정리
- [x] 포트폴리오 프로젝트 부분에서 작성한 포트폴리오 페이지에 대한 리서치 자료 정리
